
INSERT INTO categories (id, nama_kategori)
VALUES
(1,'UMUM'),
(2,'PEMERINTAHAN'),
(3,'POLITIK'),
(4,'KEAMANAN DAN KETERTIBAN'),
(5,'KESEJAHTERAAN RAKYAT'),
(6,'PEREKONOMIAN'),
(7,'PEKERJAAN UMUM DAN KETENAGAAN'),
(8,'PENGAWASAN'),
(9,'KEPEGAWAIAN'),
(10,'KEUANGAN'),
(11,'NON KEUANGAN DAN NON KEPEGAWAIAN');